name: 🚧 Setup
description: Setup the monorepo

runs:
  using: 'composite'

  steps:
    - name: 🚧 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: 🚧 Setup Node
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version-file: '.nvmrc'

    - name: 📦 Install
      shell: bash
      run: yarn

