compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  react-native-google-signin:
    npmAuthToken: "${NPM_GITHUB_PACKAGES_TOKEN:-not-set}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interractive-filter.cjs
    spec: "https://raw.githubusercontent.com/eyolas/yarn-plugin-interractive-filter/master/bundles/%40yarnpkg/plugin-interractive-filter.js"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
