yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: node-modules
enableGlobalCache: false
compressionLevel: mixed

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interractive-filter.cjs
    spec: 'https://raw.githubusercontent.com/eyolas/yarn-plugin-interractive-filter/master/bundles/%40yarnpkg/plugin-interractive-filter.js'
