services:
  - type: web
    name: api
    env: node
    branch: main
    autoDeploy: false # Deployed via cd.yml (Github Actions)
    buildCommand: yarn && yarn api build
    startCommand: yarn api prisma migrate deploy && yarn api start:prod
    healthCheckPath: /health
    envVars:
      - fromGroup: api-vars
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: api-redis
          property: connectionString
      - key: SUBGRAPH_GQL_URL
        sync: false
      - key: CHAIN
        value: testnet
      - key: WALLET_ADDRESS
        sync: false
      - key: WALLET_PRIVATE_KEY
        sync: false
    region: oregon
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
      targetCPUPercent: 70
    domains:
      - api.metasafe.fi
  - type: redis
    name: api-redis
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: api-db
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

envVarGroups:
  - name: api-vars
    envVars:
      - key: SESSION_SECRET
        generateValue: true
