services:
  - type: web
    name: api
    branch: main
    env: node
    autoDeploy: false
    buildCommand: yarn && yarn api build
    startCommand: yarn api prisma migrate deploy && yarn api start:prod
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: api-redis
          property: connectionString
      - key: DOTENV_KEY
        sync: false
    region: oregon
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 70
      targetMemoryPercent: 80
    domains:
      - api.zallo.io

  - type: redis
    name: api-redis
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: api-postgres
    region: oregon
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
