services:
  - type: web
    name: api
    branch: main
    env: node
    autoDeploy: false
    buildCommand: yarn && yarn api build
    startCommand: yarn api prisma migrate deploy && yarn api start:prod
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: api-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: CHAIN
        value: testnet
      - key: WALLET_PRIVATE_KEY
        sync: false
      - key: SUBGRAPH_GQL_URL
        sync: false
      - key: PROXY_FACTORY_TESTNET
        sync: false
      - key: APOLLO_GRAPH_REF
        value: zallo-api-prod@current
      - key: APOLLO_KEY
        sync: false
      - key: EXPO_TOKEN
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: APOLLO_SCHEMA_REPORTING
        value: true
    region: oregon
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 70
      targetMemoryPercent: 80
    domains:
      - api.zallo.io

  - type: redis
    name: api-redis
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: api-postgres
    region: oregon
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
