services:
  - type: web
    name: api
    env: node
    branch: render # TODO: change to main
    autoDeploy: false # Deployed via cd.yml (Github Actions)
    buildCommand: yarn set version stable && yarn && yarn api build && yarn api prisma migrate deploy
    startCommand: yarn api start:prod
    healthCheckPath: /health
    envVars:
      - fromGroup: api-vars
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
          property: connectionString
      - key: CHAIN
        value: testnet
      - key: WALLET_ADDRESS_TESTNET
        sync: false
      - key: WALLET_PRIVATE_KEY_TESTNET
        sync: false
    region: oregon
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
      targetCPUPercent: 70
    domains:
      - api.metasafe.fi

databases:
  - name: api-db
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

envVarGroups:
  - name: api-vars
    envVars:
      - key: SESSION_SECRET
        generateValue: true
