# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
solc = "0.8.25"
src = "src"
libs = ["node_modules"]
out = "out"
test = 'test'
cache_path = 'cache-forge'
# Compiler options
via_ir = true
# zkSync options
zksync = true
mode = "3"
# is_system = true
# detect_missing_libraries = true

[profile.default.fuzz]
runs = 32

[rpc_endpoints]
zksync_mainnet = "${RPC_ZKSYNC_MAINNET}"
zksync_sepolia = "${RPC_ZKSYNC_SEPOLIA}"


[profile.ci]
verbosity = 3

[profile.ci.fuzz]
runs = 256
