# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
solc = "0.8.26"
src = "src"
libs = ["node_modules"]
out = "out"
test = 'test'
cache_path = 'cache-forge'
# Compiler options
via_ir = true

[profile.default.zksync]
zksolc = "1.5.2"
eravm_extensions = true
optimizer_mode = '3'

[profile.default.fuzz]
runs = 32

[rpc_endpoints]
zksync_mainnet = "${RPC_ZKSYNC_MAINNET:-https://mainnet.era.zksync.io}"
zksync_sepolia = "${RPC_ZKSYNC_SEPOLIA:-https://sepolia.era.zksync.dev}"


[profile.ci]
verbosity = 3

[profile.ci.fuzz]
runs = 256
