version: '3.8'

services:
  redis:
    build: .
    container_name: zallo-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - zallo-redis:/data

volumes:
  zallo-redis:
    driver: local
