app = "zallo-production-edgedb"
primary_region = "lax"  # Los Angeles

swap_size_mb = 1024

[build]
  image = "edgedb/edgedb:5.0-beta.2"

[env]
  EDGEDB_SERVER_PORT = 10700 # default
  EDGEDB_SERVER_TLS_CERT_MODE = "generate_self_signed"


  # Secrets
  # EDGEDB_SERVER_PASSWORD      # Randomly generated
  # EDGEDB_SERVER_TLS_KEY       # Exported from app after first start
  # EDGEDB_SERVER_TLS_CERT      # ^
  ## Remote postgres
  # EDGEDB_SERVER_BACKEND_DSN   # fly pg attach ... --variable-name EDGEDB_SERVER_BACKEND_DSN


[[services]]
  internal_port = 10700
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    type = "connections"
    # These numbers are from nowhere and testing is needed
    soft_limit = 250
    hard_limit = 500

  [[services.http_checks]]
    interval = "10s"
    grace_period = "60s"
    method = "get"
    path = "/server/status/alive"
    protocol = "https"
    timeout = "2s"
    tls_skip_verify = true

[metrics]
  port = 10700
  path = "/metrics"

# Local postgres
[mounts]
  source = "edgedb_data"
  destination = "/var/lib/edgedb" # EDGEDB_SERVER_DATADIR (/var/lib/edgedb/data) parent