specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Safe
    network: {{network}}
    source:
      abi: Safe
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      abis:
        - name: Safe
          file: ./abi/Safe-fixed.json
      entities:
        - Safe
        - Approver
        - Group
        - GroupApprover
        - Deposit
        - Transaction
        - TransactionApprover
      eventHandlers:
        - event: GroupAdded((address,uint256)[])
          handler: handleGroupAdded
        - event: GroupRemoved(bytes32)
          handler: handleGroupRemoved
        - event: Deposit(address,uint256)
          handler: handleDeposit
        - event: Execution((address,uint256,bytes,uint256),bytes32,address[],address,bytes)
          handler: handleExecution
