app = "edgedb-prod"
primary_region = "lax"  # Los Angeles

[build]
  image = "edgedb/edgedb"

[env]
  EDGEDB_SERVER_PORT = 8080
  EDGEDB_SERVER_BACKEND_DSN_ENV = "DATABASE_URL"
  EDGEDB_SERVER_TLS_CERT_MODE = "generate_self_signed"

  # Secrets
  # DATABASE_URL                # fly pg attach ...
  # EDGEDB_PASSWORD             # Randomly generated
  # EDGEDB_SERVER_TLS_KEY       # Exported from app after first start
  # EDGEDB_SERVER_TLS_CERT      # ^

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    type = "connections"
    # These numbers are from nowhere and testing is needed
    soft_limit = 250
    hard_limit = 500

  [[services.http_checks]]
    interval = 10000
    grace_period = 5000
    method = "get"
    path = "/server/status/alive"
    protocol = "https"
    timeout = 2000
    tls_skip_verify = true

[metrics]
  type = "prometheus"
  port = 8080
  path = "/metrics"