app = "zallo-production-edgedb"
primary_region = "lax"  # Los Angeles

swap_size_mb = 2048

[build]
  image = "edgedb/edgedb:3.4"

[env]
  EDGEDB_SERVER_PORT = 10700 # default
  EDGEDB_SERVER_TLS_CERT_MODE = "generate_self_signed"
  EDGEDB_SERVER_DATADIR = "/var/lib/edgedb/data" # default; only for local postgres instance

  # Secrets
  # EDGEDB_PASSWORD             # Randomly generated
  # EDGEDB_SERVER_TLS_KEY       # Exported from app after first start
  # EDGEDB_SERVER_TLS_CERT      # ^

  # For remote postgres instance
  # EDGEDB_SERVER_BACKEND_DSN_ENV = "DATABASE_URL"
  # DATABASE_URL secret                # fly pg attach ... # only for remote postgres instance

[[services]]
  internal_port = 10700
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    type = "connections"
    # These numbers are from nowhere and testing is needed
    soft_limit = 250
    hard_limit = 500

  [[services.http_checks]]
    interval = "10s"
    grace_period = "60s"
    method = "get"
    path = "/server/status/alive"
    protocol = "https"
    timeout = "2s"
    tls_skip_verify = true

[metrics]
  port = 10700
  path = "/metrics"

# Only required for local postgres instance
[mounts]
  source = "edgedb_data"
  destination = "/var/lib/edgedb" # EDGEDB_SERVER_DATADIR parent; can't be /data dir directly