app = "edgedb-prod"
primary_region = "lax"  # Los Angeles

[build]
  image = "edgedb/edgedb"

[env]
  EDGEDB_SERVER_PORT = 8080
  EDGEDB_SERVER_BACKEND_DSN_ENV = "DATABASE_URL"
  EDGEDB_SERVER_TLS_CERT_MODE = "generate_self_signed"

  # Secrets
  # EDGEDB_PASSWORD             # Randomly generated
  # DATABASE_URL                # fly pg attach ...
  # EDGEDB_SERVER_TLS_KEY       # Exported from app after first start
  # EDGEDB_SERVER_TLS_CERT      # ^


[http_service]
  internal_port = 8080
  force_https = true
  # TODO: re-enable auto start/stop once min instances is supported
  auto_stop_machines = false
  auto_start_machines = false
  [http_service.concurrency]
        type = "connections"
        hard_limit = 25
        soft_limit = 20