app = "zallo-production-edgedb"
primary_region = "lax"  # Los Angeles

swap_size_mb = 1024

[build]
  image = "edgedb/edgedb:3.2"

[env]
  EDGEDB_SERVER_PORT = 8080
  EDGEDB_SERVER_BACKEND_DSN_ENV = "DATABASE_URL"
  EDGEDB_SERVER_TLS_CERT_MODE = "generate_self_signed"

  # Secrets
  # DATABASE_URL                # fly pg attach ...
  # EDGEDB_PASSWORD             # Randomly generated
  # EDGEDB_SERVER_TLS_KEY       # Exported from app after first start
  # EDGEDB_SERVER_TLS_CERT      # ^

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    type = "connections"
    # These numbers are from nowhere and testing is needed
    soft_limit = 250
    hard_limit = 500

  [[services.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "get"
    path = "/server/status/alive"
    protocol = "https"
    timeout = "2s"
    tls_skip_verify = true

[metrics]
  type = "prometheus"
  port = 8080
  path = "/metrics"