app = "zallo-production-api"
primary_region = "iad" # Ashburn, Virginia

[build]
  dockerfile = "Dockerfile"

[deploy]
  # Runs instead of image CMD
  release_command = "yarn db:prepare"

[env]
  API_PORT = 3000

  # Secrets
  # DOTENV_KEY                  # npx dotenv-vault keys

[processes]
  web    = "yarn start:web"
  worker = "yarn start:worker"

[http_service]
  processes = ["web"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
  [http_service.concurrency]
    type = "requests"
    # Example used in docs, testing is needed
    soft_limit = 500
    hard_limit = 1000
  
  [[http_service.checks]]
    path = "/live"
    method = "GET"
    interval = "10s"
    timeout = "5s"
    grace_period = "15s"

[[services]]
  processes = ["worker"]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

   [[services.http_checks]]
    path = "/live"
    method = "GET"
    interval = "10s"
    timeout = "5s"
    grace_period = "15s"
