app = "edgedb-prod"
primary_region = "lax"  # Los Angeles

[build]
  image = "edgedb/edgedb:3.0"

[env]
  EDGEDB_SERVER_PORT = 8080
  EDGEDB_SERVER_BACKEND_DSN_ENV = "DATABASE_URL"
  EDGEDB_SERVER_TLS_CERT_MODE = "generate_self_signed"

  # Secrets
  # DATABASE_URL                # fly pg attach ...
  # EDGEDB_PASSWORD             # Randomly generated
  # EDGEDB_SERVER_TLS_KEY       # Exported from app after first start
  # EDGEDB_SERVER_TLS_CERT      # ^


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
        type = "connections"
        # These numbers are from nowhere and testing is needed
        soft_limit = 50
        hard_limit = 100