app = "zallo-api-prod"
primary_region = "lax" # Los Angeles

[build]
dockerfile = "Dockerfile"

[env]
API_PORT = 3000

# Secrets
# DOTENV_KEY                  # npx dotenv-vault keys


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
  [http_service.concurrency]
    type = "requests"
    # Example used in docs, testing is needed
    soft_limit = 500
    hard_limit = 1000
