# Deploy when CI succeeds on a push to main
name: CD

on:
  workflow_run:
    branches: [main]
    workflows: ['CI']
    type: [completed]

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

env:
  CHAIN: testnet
  INFURA_ID: ${{ secrets.INFURA_ID }}
  INFURA_SECRET: ${{ secrets.INFURA_SECRET }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  API_URL: ${{ secrets.API_URL }}
  SUBGRAPH_GQL_URL: ${{ secrets.SUBGRAPH_GQL_URL }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  subgraph:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🚧 Configure
        run: yarn subgraph configure:testnet

      - name: 🚧 Auth
        run: yarn subgraph auth ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

      - name: 🏗️ Generate
        run: yarn subgraph generate

      - name: 🏗️ Build
        run: yarn subgraph build

      - name: 🚀 Deploy
        run: yarn subgraph deploy:metasafe

  api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_DEPLOY_HOOK }}
          method: POST

  app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 🚧 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Prebuild
        run: yarn app prebuild

      - name: 🏗️ Build
        run: yarn app eas:build

      - name: 🚀 Publish update
        run: yarn app eas:publish-update
