# Deploy to dev when CI succeeds on a push to main
name: CD

on:
  workflow_run:
    branches:
    # branches: [main]
    workflows: ['CI']
    type: [completed]

jobs:
  subgraph:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🚧 Configure
        run: yarn subgraph configure:ropsten

      - name: 🚧 Auth
        run: yarn subgraph auth ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

      - name: 🏗️ Build
        run: yarn subgraph build

      - name: 🚀 Publish
        run: yarn subgraph publish

  app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 🚧 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn app build

      - name: 🚀 Publish
        run: yarn app publish

  api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚀 Heroku - Build, Push and Release
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          process_type: web
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          # docker_options: ""
