name: Deployment

on:
  push:
    branches: [main]

concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    environment: main - api
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DEPLOY_HOOK }}
          method: POST

  app:
    environment: main - app
    runs-on: ubuntu-latest

    env:
      DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v3

      - name: 🚧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: 🚧 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_API_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Prebuild
        run: yarn app prebuild

      # Update both android & ios, but not web (thus not all). Web build fails when bundling @react-native-community/blur
      - name: 🚀 Publish update (Android)
        run: yarn app eas update --auto --non-interactive --platform android

      - name: 🚀 Publish update (iOS)
        run: yarn app eas update --auto --non-interactive --platform ios

  subgraph:
    environment: main - subgraph
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v3

      - name: 🚧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🚧 Auth
        run: yarn subgraph auth ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

      - name: 🏗️ Generate
        run: yarn subgraph generate

      - name: 🏗️ Build
        run: yarn subgraph build:testnet

      - name: 🚀 Deploy
        run: yarn subgraph deploy ${{ vars.SUBGRAPH_ID }}

  # Docs deployment is handled by Netlify
