# Perform tests when pushing or creating a PR to any branch
name: Integration - Development

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - dev

env:
  RELEASE_ENV: development
  SUBGRAPH_GQL_URL: ${{ secrets.SUBGRAPH_GQL_URL_DEV }}

jobs:
  lib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn lib build

      - name: 🧪 Test
        run: yarn lib test

  contracts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Checkout zksync-local
        uses: actions/checkout@v3
        with:
          repository: hbriese/zksync-local
          path: zksync-local

      - name: 🚧 Start local zksync node
        run: (cd zksync-local && ./start.sh)

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn contracts build

      - name: 💤 Wait for local zksync node to start
        run: sleep 90

      - name: 🧪 Test
        run: yarn contracts test

  subgraph:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🚧 Configure
        run: yarn subgraph configure:testnet

      - name: 🏗️ Generate
        run: yarn subgraph generate

      - name: 🏗️ Build
        run: yarn subgraph build

  api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn api build

      - name: 🧪 Test
        run: yarn api test

  app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v2

      - name: 🚧 Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Pre-Build
        run: yarn app prebuild

      - name: 🧪 Test
        run: yarn app test
