name: Tests

on:
  push:
    branches-ignore: [main]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  lib:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: 📦 Install
        run: yarn

      - name: 🧪 Test
        run: yarn lib test

  contracts:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: 🚧 Start zkSync local testnet node
        uses: dutterbutter/era-test-node-action@latest

      - name: 📦 Install
        run: yarn

      - name: 🧪 Test
        run: yarn contracts test

  api:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: 💾 Setup EdgeDB
        uses: edgedb/setup-edgedb@v1
        with:
          instance-name: tests

      - name: 💾 Initialize EdgeDB project
        run: (cd api && edgedb project init --non-interactive)

      - name: 📦 Install
        run: yarn

      - name: 🏗️ Build
        run: yarn api build

      - name: 🧪 Test
        run: yarn api test

  app-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: 📦 Install
        run: yarn

      - name: 👕 Lint
        run: yarn app lint

      - name: 🧪 Test
        run: yarn app test

  app-web-build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: 📦 Install
        run: yarn

      - name: 🏗️ Build
        run: yarn app build:web
# site:
#   runs-on: ubuntu-latest

#   steps:
#     - name: 🚧 Checkout
#       uses: actions/checkout@v4

#     - name: 🚧 Setup Node
#       uses: actions/setup-node@v4
#       with:
#         cache: 'yarn'
#         node-version-file: '.nvmrc'

#     - name: 📦 Install
#       run: yarn

#     - name: 🏗️ Build
#       run: yarn site build

#     - name: 🧪 Typecheck
#       run: yarn site typecheck
