name: Tests

on:
  push:
    branches-ignore: [main]

jobs:
  lib:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn lib build

      - name: 🧪 Test
        run: yarn lib test

  contracts:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4

      - name: 🚧 Checkout zksync-local
        uses: actions/checkout@v4
        with:
          repository: hbriese/zksync-local
          path: zksync-local

      - name: 🚧 Start local zksync node
        run: (cd zksync-local && ./start.sh)

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn contracts build

      - name: 💤 Wait for local zksync node to start
        run: sleep 90

      - name: 🧪 Test
        run: yarn contracts test

  site:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn site build

      - name: 🧪 Typecheck
        run: yarn site typecheck

  api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 💾 Setup EdgeDB
        uses: edgedb/setup-edgedb@v1
        with:
          instance-name: tests

      - name: 💾 Initialize EdgeDB project
        run: edgedb project init --non-interactive

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn build

      - name: 🧪 Test
        run: yarn test

  app-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Pre-Build
        run: yarn app prebuild

      - name: 🧪 Test
        run: yarn app test

  app-web-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn app build:web

  app-web-preview:
    environment: main - app
    runs-on: ubuntu-latest

    env:
      DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
      NODE_OPTIONS: '--max-old-space-size=4096'
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}

    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@v4

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 📦 Install
        run: yarn install

      - name: 🏗️ Build
        run: yarn app build:web

      # - name: 🚀 Publish
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --filter app --dir dist
      #   env:
      #     NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: 🚀 Publish
        uses: nwtgck/actions-netlify@v2.0 # https://github.com/nwtgck/actions-netlify
        with:
          publish-dir: './app/dist'
          alias: deploy-preview-${{ github.event.number }}
        timeout-minutes: 1
